move to phusion baseimage
 * v1.0 tag actually doesn't run (!)
   Error: Failed to early mount API filesystems, freezing.
 * v2.0 tag crashes because of missing /sbin/init
   When installing init, it crashes with the same error
 * problems fixed by switching to phusion/baseimage:0.11
   which is based on ubuntu 18.04